### ISSUE TITLE
Modifying IgBLAST parameters

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/clonomapbridge#8]
Another thing I stumbled upon in https://github.com/era7bio/tcrbsilvia/issues/5.

At the moment, if you want to reuse the `igblastAnnotation` loquat in another project, but run IgBLAST with slightly different parameters, you basically can't (so I had to copy-paste most of the code). 

The reason is that `annotation.clonotypesCmd` is not really modifiable, so probably this should be addressed in the repseqmiodx repo. I just wanted this to the discussion..

https://github.com/era7bio/asdfjkl/blob/d681bcf750537948de6076e571f573d842c834da/src/main/scala/loquats/annotation.scala#L70-L77

**Comment by agarciamontoro** [comment]
I cannot see https://github.com/era7bio/tcrbsilvia/issues/5.

Anyway, I don't know about this very specific problem, but if `repseqmiodx` is to be used in future projects, it wouldn't hurt to rethink some bits and making it more modular (?)

**Comment by agarciamontoro** [comment]
This will not be fixed here, so closing it.
